spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

# Configuration Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,hibernate-stats
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    hibernate-stats:
      enabled: true
  metrics:
    enable:
      hibernate: true
      jvm: true
      system: true

logging:
  level:
    org:
      springframework:
         security: DEBUG
    # Logs pour le monitoring des performances
    com.ecommerce.aspects: INFO
    com.ecommerce.services.DatabasePerformanceMonitoringService: INFO
